# STAGES TO EXECUTE
stages:
  find_galaxies: true
  properties_core: true
  properties_ptype_specific: true
  properties_local_environment: true

# PTYPES TO PROCESS
# WARNING: this removes the ptype entirely, for example, star: false will stop FOF6D from running
process_ptypes:
  gas: true
  star: true
  dm: true
  bh: true

# CONSTANTS
MINIMUM_STARS_PER_GALAXY: 16
MINIMUM_DM_PER_HALO: 24
nHlim: 0.13
Tlim: 1.0e+5
XH: 0.76

# FOF6D
b: 0.02 
vel_LL: 1 

# AGGREGATE PROPERTIES
radial_quantiles:
  r20: 0.2
  half_mass: 0.5
  r80: 0.8
# NOTE: these need to be lists even if single-valued for the unpacker
aperture_size: [30] 
virial_factors: [200, 500, 2500]
density_radii: [300, 1000, 3000]

# PARALLELISM
nproc: 4 # cores per node for joblib