# STAGES TO EXECUTE

stages:
  find_galaxies:                  true
  properties_core:                true
  properties_ptype_specific:      true
  properties_local_environment:   true

# PTYPES TO PROCESS

# WARNING: this removes the ptype entirely, for example, star: false will stop FOF6D from running
process_ptypes:
  gas:    true
  star:   true
  dm:     true
  bh:     true

# GROUP THRESHOLDS

MINIMUM_STARS_PER_GALAXY:   16
MINIMUM_DM_PER_HALO:        24

# PHYSICS CRITERIA

nH_lim:  0.13     # density above which gas is considered dense
T_lim:   1.0e+5   # temperature below which gas is considered cold
XH:     0.76      # hydrogen fraction
FRAD:   0.1       # radiative efficiency of accretion (epsilon)
MU:     0.6       # mean mass per-particle (gas); computed directly, if not available in snapshot, uses this

# FOF6D ALGORITHM

b:                0.02  # position-space linking length = b * mean_interparticle_separation
velocity_factor:  1     # velocity-space linking length = velocity_factor * local_velocity_dispersion

# AGGREGATE PROPERTIES

radial_quantiles: # name: fraction of enclosed mass
  r20:        0.2
  half_mass:  0.5
  r80:        0.8
# NOTE: these need to be lists for the unpacker
aperture_size:    [30]                # kpc
virial_factors:   [200, 500, 2500]    # factor * critical density
density_radii:    [300, 1000, 3000]   # kpc

# PARALLELISM

cores_per_rank: 4 # number of VPU cores assigned to each MPI rank

# LOGGING

terminal_output_level: "INFO" # how chatty do you want Octavian to be (set to WARNING for runtime-critical notifications)