name: Build Documentation

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: pip install .
      - run: pip install ".[docs]"
      - run: sphinx-build -W -b html docs/ docs/_build/html  # W means link rot and missing images fail CI